  Answers of Theory Questions

1. NumPy is a fundamental library in Python for scientific computing. It offers powerful features for working with multidimensional arrays and performing various mathematical operations efficiently. It is widely used because it is an is an open source Python library that has a wide range of inbuilt functions.

2. Broadcasting is a mechanism in NumPy that allows performing operations on arrays of different shapes under certain conditions. When operands have different shapes, NumPy expands the smaller array to match the larger one in a specific way to perform element-wise operations.

3. A Pandas DataFrame is one of the core data structures provided by the Pandas library in Python. It is used for storing, manipulating, and analyzing tabular data (data arranged in rows and columns), similar to an Excel spreadsheet or SQL table.

4. The groupby() method in Pandas is used to split data into groups, apply some operation on each group, and then combine the results. It is extremely useful for data analysis, especially when summarizing or aggregating data.

   The steps are as follows:-

   Split - divide the DataFrame into groups based on some column(s)

   Apply - perform an operation (sum, mean, count, max, min, etc.)

   Combine - merge the results back into a new DataFrame

This is known as the Split-Apply-Combine process.

5. Seaborn is preferred for statistical visualizations in Python because it is built specifically to make statistical plotting simpler, more attractive, and more powerful than using Matplotlib alone.

6. Python lists and NumPy arrays are both used to store collections of data, but they differ significantly in their characteristics and use cases.

  Data Type Homogeneity:

Python List: Can store heterogeneous data types, meaning elements within a single list can be of different types (eg  integers, floats, strings, or even other lists).

NumPy Array: Stores homogeneous data types, requiring all elements within an array to be of the same type. This allows for more efficient storage and computation.

  Performance:

Python List: Generally less efficient for numerical operations on large datasets due to the overhead of storing and managing heterogeneous data types. Operations often require explicit loops.

NumPy Array: Optimized for numerical computations, offering significantly better performance for large datasets. This is achieved through vectorized operations, which are implemented in C and Fortran for speed.

  
  Memory Efficiency:

Python List: Less memory efficient, especially for large datasets, as each element is a full Python object with its own type information and reference count.

NumPy Array: More memory efficient for large numerical datasets because it stores data in contiguous memory blocks and avoids the overhead of individual Python objects for each element.


 Functionality:


Python List: Provides general-purpose list manipulation methods (eg, append(), insert(), remove()).

NumPy Array: Offers a rich set of mathematical functions and operations optimized for array manipulation, including advanced indexing, broadcasting, and linear algebra routines.

 Use Cases:


Python List: Suitable for general-purpose tasks where flexibility in data types and dynamic resizing are important, such as storing diverse collections of objects or managing queues.

NumPy Array: Ideal for numerical computing, scientific applications, and data analysis involving large datasets where performance and memory efficiency are crucial, such as image processing, machine learning, and simulations.

7. A heatmap is a data visualization technique that uses color intensity to represent the magnitude of values in a matrix or table. It helps us to  quickly identify patterns, trends, and correlations in data. It should be used to visualize correlations between variables, analyze patterns in large datasets compare values across two dimensions and to visualize density or frequency.

8. In NumPy, the term “vectorized operation” refers to performing operations on entire arrays (vectors, matrices) at once without using explicit Python loops.

9. Matplotlib and Plotly are both powerful Python visualization libraries, but they serve different purposes and are built with different strengths in mind. The differences are as follows:-

   Static vs Interactive Plots

   Matplotlib- Primarily designed for static, publication-quality plots. Plots are images (PNG, PDF, SVG). Interaction is minimal unless using additional tools.

   Plotly- Built for interactive visualizations (zoom, hover tooltips, sliders). Generates HTML-based charts ideal for dashboards and web apps.


   Ease of Use

   Matplotlib- Low-level library → gives full control but requires more code. Often need to manually manage labels, ticks, layout, etc.

   Plotly- Higher-level interactions come built-in. Complex visuals (3D plots, maps, subplots) can be created with fewer lines of code.


   Appearance and Styling

   Matplotlib- Default style is simple and classic. Highly customizable but requires manual styling. Best for scientific publications (e.g journals).

   Plotly- Modern, colorful, and attractive by default. Interactive legends, animations, and hover details included automatically.


   Use Cases

   When to use Matplotlib- Academic research, Static charts for reports and papers , Precise control over every visual element, Integration with NumPy/SciPy workflow ,Reproducible static plots for Jupyter notebooks
   
   
   When to use Plotly- Dashboards (especially with Plotly Dash), Web-based visualizations, Interactive data exploration, Presentations where user interaction is helpful, 3D plots, maps, time-series with zoom/hover


   Supported Plot Types

   Matplotlib: 2D plots (line, bar, histogram, scatter), Limited 3D support (via mpl_toolkits.mplot3d), Custom shapes, subplots, and annotations

   Plotly: Everything Matplotlib can do +,Interactive 3D plots, Geographical maps, Animations, Interactive heatmaps and treemaps, Financial charts (candlesticks, OHLC)


   Performance

   Matplotlib: Faster for large static datasets. Ideal for millions of points when interaction isn't required.

   Plotly: Interactive rendering can be slower for extremely large datasets. Uses JavaScript under the hood.


   Output Formats

   Matplotlib: PNG, JPG, SVG, PDF, Good for print media

   Plotly: HTML, JSON, Embeddable interactive visuals for web apps, Also supports static export (via Kaleido)


10. The significance of hierarchical indexing in Pandas (also called MultiIndex) is a powerful feature that allows us to work with multiple levels of indexing on rows or columns. It enables us to handle and analyze higher-dimensional data in a 2-dimensional DataFrame.

11. The role of Seaborn's pairplot() function) is used to create a grid of plots that visualizes pairwise relationships between multiple variables in a dataset. It is one of the most powerful exploratory data analysis (EDA) tools in Seaborn.

12. The describe() function in Pandas is used to generate summary statistics for numerical and categorical data in a DataFrame or Series. It provides a quick overview of the distribution and key statistical measures of our dataset.

13. Handling missing data in Pandas is extremely important because missing values can significantly affect the accuracy, reliability, and interpretation of our data analysis or machine learning models.

14. The benefits of using Plotly for data visualization are as follows:-

    Interactivity: Plotly's main strength is its built-in interactive features, such as zooming, panning, hovering over data points for detailed information (tooltips), and incorporating interactive elements like sliders and buttons. This allows for dynamic data exploration and a better storytelling experience compared to static charts.

    Wide Range of Plot Types: It supports a diverse and extensive variety of charts, from basic bar and line charts to complex 3D plots, heatmaps, geospatial maps, and more, enabling users to visualize different types of data effectively

    Web Compatibility & Integration: Visualizations are browser-friendly, built on D3.js, HTML, and CSS, and can be easily embedded into web applications and dashboards using frameworks like Dash, Flask, or Jupyter Notebooks. They can also be exported as interactive HTML files.

    Multi-Language Support: Plotly provides APIs for several programming languages, including Python, R, and JavaScript, catering to a wide range of users in the data science community.

    Ease of Use: With high-level APIs like Plotly Express, users can generate complex and appealing plots with minimal code, making it accessible for quick data exploration and analysis.

    Customization: Plotly offers extensive options for customizing the appearance of plots, including colors, fonts, labels, and annotations, to meet specific branding or presentation needs.
    
    Open-Source and Supportive Community: It is an open-source library, meaning it's free to use, and has an active and helpful community for support and collaboration.

15. NumPy handles multidimensional arrays using a powerful data structure called the ndarray (N-dimensional array), which allows efficient storage and manipulation of data in 2D, 3D, or even higher dimensions.

16. Bokeh is a powerful Python library used for creating interactive, web-ready data visualizations. Its main role is to help developers build dynamic, scalable, and browser-based plots and dashboards with very little JavaScript.

17. The difference between apply() and map() in Pandas are as follows:-

    map() in Pandas- Used only with Series, Performs element-wise transformations, Ideal for replacing values using a dictionary or mapping function

    apply() in Pandas- Works on both Series and DataFrame, Can apply a function on each element, each row (axis=1),
    each column (axis=0), Suitable for complex operations

18. The advanced features of NumPy are as follows:-
    
    Broadcasting: This is a powerful mechanism that allows NumPy to work with arrays of different shapes during arithmetic operations by "broadcasting" the smaller array across the larger one. This avoids the need for explicit loops and memory-intensive data duplication, making code more efficient and concise.
    
    Advanced Indexing and Slicing: Beyond basic slicing, NumPy supports advanced indexing with lists or arrays of integers to select specific elements and using boolean arrays to filter elements based on a condition.
    
    Vectorized Operations: NumPy performs mathematical operations on entire arrays at once, known as vectorization, which is significantly faster than using traditional Python loops.
    
    Universal Functions (ufuncs): These are functions that operate on ndarrays element-wise, such as np.sin(), np.cos(), and np.exp(), providing a fast and efficient way to perform calculations.

    Specialized modules and functionalities

    Linear Algebra: NumPy includes a comprehensive linear algebra module that performs operations like matrix multiplication, finding the determinant, inverse, rank, and trace.
    
    Fourier Transforms: It has built-in capabilities to perform Fourier transforms on arrays.
    
    Array Manipulation: Advanced array manipulation functions include stacking arrays vertically (vstack) or horizontally (hstack), and splitting arrays along different axes.
    
    Random Number Generation: NumPy provides a random module for generating random numbers for a wide range of distributions and scenarios.
    
    Statistical Functions: It offers a wide array of functions for statistical analysis, such as calculating the mean, median, variance, and finding the maximum or minimum values in an array.
    
    Data Type Handling: NumPy arrays are homogeneous, meaning they store elements of a single data type, which improves performance and memory efficiency. It also provides tools for working with a variety of data types, including datetime64 for date and time functionality.

19. Pandas provides powerful, built-in tools that make time series analysis simple, efficient, and intuitive. It is one of the main reasons Pandas is widely used in finance, analytics, forecasting, and scientific research.

20. A pivot table in Pandas is a powerful tool for data summarization and analysis, similar to Excel pivot tables. It allows us to reorganize, aggregate, and analyze data efficiently.

21. NumPy's array slicing is faster than Python's list slicing due to how data is stored and accessed in memory, along with NumPy's underlying C implementation.

22. Common use cases for Seaborn are as follows:-
    
    Exploring Relationships between Variables:

    Scatter plots (sns.scatterplot): To visualize the relationship between two continuous variables and identify trends, clusters, or outliers.

    Line plots (sns.lineplot): To show trends over time or across different categories, especially for continuous data.

    Pair plots (sns.pairplot): To visualize the relationships between all pairs of variables in a dataset, as well as the distributions of individual variables.


    Visualizing Data Distributions:

    Histograms (sns.histplot): To display the frequency distribution of continuous data, revealing its shape, center, and spread.

    Kernel Density Estimates (KDEs) (sns.kdeplot): To visualize the probability density function of a continuous variable, providing a smoothed representation of its distribution.

    Box plots (sns.boxplot): To display the distribution of data and identify outliers, particularly useful for comparing distributions across different categories.

    Violin plots (sns.violinplot): To combine the features of box plots and KDEs, showing both the distribution and central tendency of data across categories.

    Comparing Categorical Data:

    Bar plots (sns.barplot): To visualize counts, frequencies, percentages, or averages of categorical variables.

    Count plots (sns.countplot): To display the number of occurrences of each category in a categorical variable.

    Cat plots (sns.catplot): A versatile function to create various types of categorical plots, such as box plots, violin plots, and bar plots, with options for faceting and grouping.

    Visualizing Data in Grid Formats:

    Heatmaps (sns.heatmap): To visualize data in a grid format, often used to display correlation matrices or patterns in tabular data.

    Enhancing Plot Aesthetics:
    
    Seaborn provides built-in themes, color palettes, and functions to easily create visually appealing plots with minimal code, improving the overall presentation of data insights.


    Facilitating Exploratory Data Analysis (EDA):

    Seaborn's dataset-oriented API and high-level functions make it easy to quickly generate a variety of plots, aiding in the initial exploration and understanding of data.


Answers of Practical Questions

1.

In [4]:
import numpy as np
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
row_sums = np.sum(arr, axis=1)
print(row_sums)



[ 6 15 24]


2.

In [5]:
import pandas as pd

# Sample DataFrame
data = {
    'A': [10, 20, 30, 40],
    'B': [5, 15, 25, 35]
}

df = pd.DataFrame(data)

# Find the mean of column 'A'
mean_A = df['A'].mean()

print("Mean of column A:", mean_A)



Mean of column A: 25.0


3.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data
x = np.array([5, 7, 8, 7, 2, 17, 2, 9, 4, 11, 12, 9, 6])
y = np.array([99, 86, 87, 88, 111, 86, 103, 87, 94, 78, 77, 85, 86])

plt.scatter(x, y)
plt.title('Basic Scatter Plot')
plt.xlabel('X Values')
plt.ylabel('Y Values')
plt.show()


4.

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [2, 3, 2, 3, 2]
}

df = pd.DataFrame(data)
corr_matrix = df.corr()
print(corr_matrix)
plt.figure(figsize=(6, 4))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title("Correlation Matrix Heatmap")
plt.show()


5.

In [ ]:
import plotly.express as px
import pandas as pd

# Sample data
df = pd.DataFrame({
    "Category": ["A", "B", "C", "D"],
    "Values": [10, 25, 15, 30]
})

# Create bar plot
fig = px.bar(df, x="Category", y="Values", title="Sample Plotly Bar Chart")

# Display the plot
fig.show()


6.

In [6]:
  import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Price': [100, 200, 300, 400]
})

# Add a new column based on an existing column
# Example: Add 10% tax
df['Price_with_Tax'] = df['Price'] * 1.10

print(df)



   Price  Price_with_Tax
0    100           110.0
1    200           220.0
2    300           330.0
3    400           440.0


7.

In [7]:
import numpy as np

# Create two NumPy arrays
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# Perform element-wise multiplication
result = arr1 * arr2

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Element-wise multiplication result:", result)




Array 1: [1 2 3 4]
Array 2: [5 6 7 8]
Element-wise multiplication result: [ 5 12 21 32]


8.

In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# Sample data for three lines
x = np.arange(0, 10, 1)
y1 = np.random.rand(10)
y2 = np.random.rand(10)
y3 = np.random.rand(10)

plt.plot(x, y1, label='Line 1')
plt.plot(x, y2, label='Line 2')
plt.plot(x, y3, label='Line 3')

plt.xlabel('X-axis')
plt.ylabel('Y-axis')
plt.title('Multiple Line Plot')
plt.legend()
plt.show()


9.

In [8]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Score': [45, 82, 67, 90]
})

# Define threshold
threshold = 70

# Filter rows where Score > threshold
filtered_df = df[df['Score'] > threshold]

print(filtered_df)



  Name  Score
1    B     82
3    D     90


10.

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Sample data
data = [12, 15, 17, 18, 22, 25, 25, 26, 30, 32, 35, 36, 40, 42, 45]

# Create histogram
sns.histplot(data, kde=True)   # kde=True adds a smooth density curve

plt.title("Distribution Histogram")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()


11.

In [3]:
import numpy as np

# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)        # Method 1
# C = A @ B             # Method 2 (recommended, Pythonic)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("A × B =\n", C)



Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A × B =
 [[19 22]
 [43 50]]


12.

In [ ]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("your_file.csv")

# Display the first 5 rows
print(df.head())


13.

In [ ]:
import plotly.express as px
import pandas as pd
import numpy as np

# Sample data
df = pd.DataFrame({
    "x": np.random.rand(50),
    "y": np.random.rand(50),
    "z": np.random.rand(50),
    "category": np.random.choice(["A", "B", "C"], 50)
})

# Create 3D scatter plot
fig = px.scatter_3d(
    df,
    x="x",
    y="y",
    z="z",
    color="category",
    title="3D Scatter Plot with Plotly"
)

fig.show()
